apiVersion: v1
kind: ConfigMap
metadata:
  name: raas-stage-config
  namespace: instanode
data:
  VERSION: '1'
  PORT: '3007'
  PROJECT: 'RAAS'
  DATABASE_URL: 'mysql://root:rafo85-r32hfucrU0@proddbinstanodes.internal.la-north-2.mysql.rds.myhuaweicloud.com:3306/raas'
  REDPANDA_CLIENT_ID: 'emr-service'
  REDPANDA_BROKERS: 'redpanda-0.sierradimensions.com:31092 redpanda-1.sierradimensions.com:31092 redpanda-2.sierradimensions.com:31092'
  REDPANDA_SSL: 'false'
  REDPANDA_SASL: 'false'
  REDPANDA_CONSUMER_GROUP: 'emr-service-consumer-group3'
  TOKEN_EXPIRATION: '7200'
  REDIS_URL: '127.0.0.1:6379'
  REDIS_PASSWORD: 'Gxei4ammAewZcgHisqgU'
  GROUP_ID: 'emr-service-consumer-group2'
  EMR_CONSUMER: 'iphone2'
  EMR_PRODUCER: 'iphone1'
  RAG_PRODUCER: 'iphone3'
  RAG_CONSUMER: 'iphone4'
  RAG_ALL_SUMMARY_PRODUCER: 'iphone5'
  RAG_ALL_SUMMARY_CONSUMER: 'iphone6'
  CREATE_USER: 'user_created'
  AWS_REGION: 'us-east-1'
  CLOUDFRONT_DOMAIN: 'https://d20h84dgdjnmc2.cloudfront.net'
  CLOUDFRONT_KEY_PAIR_ID: |-
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3F...
    ... (truncated for brevity — include full value here, indented properly)
  JWT_PUBLIC_KEY: ''
  BASE_URL: 'https://infra-api.instanodes.io/api/v1/'
  CHAIN_LIST_API_URL: 'https://chainid.network/chains.json'
  RABBIT_MQ: 'amqp://admin:HQ3LeLIUtzpT8S3oVX6twX@10.0.9.65:5672'
  SSE_QUEUE: 'sse_queue'
  JWT_SECRET: 'AbfI7Ep5UWT7FQR'
  JWT_EXPIRATION: '7200'
  FINAL_STEP_COUNT: '7'
  KONG_BASE_URL: http://kong.instanodes.private:8001/default
